### ISSUE TITLE
CMake/ctkMacroSetupQt.cmake: A duplicate ELSE command was found inside an IF block

### ISSUE THREAD

**Issue by samueljohn** [commontk/CTK#715]
Hi there,
when using CTK with on macOS sierra 10.12.5 with latest cmake --version `cmake version 3.8.20170518-gbc7d64` , I get the error message:

```
CMake Error at CMake/ctkMacroSetupQt.cmake:76 (else):
  A duplicate ELSE command was found inside an IF block.
Call Stack (most recent call first):
  CMakeLists.txt:410 (ctkMacroSetupQt)
```

Indeed it seems there is a duplicate `else()` in the `ctkMacroSetupQt.cmake`.
Suggesting to remove the lines (that seem duplicated from an earlier merge years ago):
https://github.com/commontk/CTK/blob/master/CMake/ctkMacroSetupQt.cmake#L76-L77

- CTK revision 7129bb0b65d52c8ad6d5940be7aed3075b675edc (latest in master as of writing this).

**Comment by jcfr** [comment]
Thanks for the report 👍  

I just pushed a PR addressing this.

I have added you as author of the commit, if you prefer not, let me know and I will only mention you in the commit message.

**Comment by samueljohn** [comment]
Wow @jcfr that is *fast*. Thanks, I am happy with author-thingy ... sorry I was to lazy to fork, and push.

**Comment by jcfr** [comment]
Great. Thanks again for the report and patch.

**Comment by ece7048** [comment]
Hello there, 
When I use ubuntu 16.04 (Xenial Xerus), cmake version 3.10.1
the ERROR of ctkMacroSetupQt.cmake still exists.
"
CMake Error at CMake/ctkMacroSetupQt.cmake:76 (else):
A duplicate ELSE command was found inside an IF block. 
"
 I have the correct file of the repository. I tried to change the else() structure with if() but the ERROR still exists. Is there any idea what happens?

**Comment by jcfr** [comment]
Hi @ece7048 , 

Could you check witch version of CTK you are using ? 

Running `git show` from the source directory should return the current git SHA.

Also if you look at the content of the file `CMake/ctkMacroSetupQt.cmake`, is it the expected version ?

**Comment by ece7048** [comment]
It was an older version with the error inside. Thank you a lot!!!

Cheers!!

**Comment by jcfr** [comment]
You are welcome :+1: Glad we were able to sort this out quickly.
